# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [1]:
!python -V

Python 3.6.8


# 1.3 Trabalhando com arrays Numpy

In [ ]:
import numpy as np

In [ ]:
km = np.loadtxt('carros-km.txt')

In [4]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [ ]:
anos = np.loadtxt('carros-anos.txt', dtype = int)

In [6]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

### Obtendo a quilometragem média por ano

In [7]:
km_media = km / (2019 - anos)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [8]:
km_media

array([2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
       1.98130769e+03, 1.53257143e+03,            nan, 7.75990000e+03,
       1.10218889e+04, 4.74725000e+03, 7.56411765e+02, 6.71000000e+02,
       4.98738889e+03,            nan, 4.14570000e+03, 3.85356667e+04,
       6.63557143e+03,            nan, 1.23620000e+04, 7.58650000e+03,
       5.95252941e+03,            nan, 3.92316000e+03, 3.67710714e+03,
                  nan,            nan, 1.93166667e+03,            nan,
       3.46164706e+03, 3.37075000e+03, 1.37104545e+03, 2.22216667e+03,
       1.77200000e+04, 1.20742857e+03, 1.81368000e+04, 1.83229167e+03,
                  nan,            nan, 5.52600000e+02,            nan,
       1.55691667e+04, 2.54762500e+03,            nan, 5.07658824e+03,
                  nan, 5.73823529e+02, 4.66300000e+03, 1.33055556e+02,
                  nan, 5.02181250e+03, 8.55540000e+03, 3.88430769e+03,
       3.56400000e+03, 7.22669231e+03, 3.92722222e+03, 3.24028000e+03,
      

In [9]:
type(km_media)

numpy.ndarray

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [10]:
2 + 2

4

### Subtração ($-$)

In [11]:
2 - 2

0

### Multiplicação ($*$)

In [12]:
2 * 3

6

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [13]:
10 / 3

3.3333333333333335

In [14]:
10 // 3

3

### Exponenciação ($**$)

In [15]:
2 ** 3

8

### Resto da divisão ($\%$)

In [16]:
10 % 3

1

In [17]:
10 % 2

0

### Expressões matemáticas

In [18]:
5 * 2 + 3 * 2

16

In [19]:
(5 * 2) + (3 * 2)

16

In [20]:
5 * (2 + 3) * 2

50

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [21]:
5 * 2

10

In [22]:
_ + 3 * 2

16

In [23]:
_ / 2

8.0

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [ ]:
ano_atual = 2019
ano_fabricacao = 2003
km_total = 44410.0

In [25]:
ano_atual

2019

In [26]:
ano_fabricacao

2003

In [27]:
km_total

44410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [28]:
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

2775.625

In [29]:
ano_atual = 2019
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

2775.625

In [30]:
ano_atual = 2019
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)

km_total = km_total + km_media
km_total

47185.625

In [31]:
ano_atual = 2019
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)

km_total += km_media
km_total

47185.625

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [ ]:
ano_atual, ano_fabricacao, km_total = 2019, 2003, 44410.0

In [33]:
ano_atual

2019

In [34]:
ano_fabricacao

2003

In [35]:
km_total

44410.0

In [36]:
ano_atual, ano_fabricacao, km_total = 2019, 2003, 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

2775.625

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [ ]:
ano_atual = 2019

In [38]:
type(ano_atual)

int

In [ ]:
km_total = 44410.0

In [40]:
type(km_total)

float

### Booleanos

In [ ]:
zero_km = True

In [42]:
type(zero_km)

bool

In [ ]:
zero_km = False

In [44]:
type(zero_km)

bool

### Strings

In [45]:
nome = 'Jetta Variant'
nome

'Jetta Variant'

In [46]:
nome = "Jetta Variant"
nome

'Jetta Variant'

In [47]:
nome = 'Jetta "Variant"'
nome

'Jetta "Variant"'

In [48]:
nome = "Jetta 'Variant'"
nome

"Jetta 'Variant'"

In [ ]:
carro = '''
  Nome
  Idade
  Nota
'''

In [50]:
type(carro)

str

### None

In [ ]:
quilometragem = None
quilometragem

In [52]:
type(quilometragem)

NoneType

# 2.4 Conversão de tipos

In [ ]:
a = 10
b = 20
c = 'Python é '
d = 'legal'

In [54]:
type(a)

int

In [55]:
type(b)

int

In [56]:
type(c)

str

In [57]:
type(d)

str

In [58]:
a + b

30

In [59]:
c + d

'Python é legal'

In [ ]:
# c + a

### Conversões de tipo

Funções int(), float(), str()

In [61]:
str(a)

'10'

In [62]:
type(str(a))

str

In [63]:
c + str(a)

'Python é 10'

In [64]:
float(a)

10.0

In [ ]:
var = 3.141592

In [66]:
int(var)

3

In [ ]:
var = 3.99

In [68]:
int(var)

3

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [69]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
  print('Verdadeiro')
else:
  print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [70]:
# Isto é um comentário
ano_atual = 2019
ano_atual

2019

In [71]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

2019

In [72]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

2019

In [73]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
  print('Verdadeiro')
else:                               # Testando se condição é falsa
  print('Falso')

Verdadeiro


### Formatação de *strings*

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [74]:
print('Olá, {}!'.format('Rodrigo'))

Olá, Rodrigo!


In [75]:
print('Olá, {}! Este é seu acesso de número {}'.format('Rodrigo', 32))

Olá, Rodrigo! Este é seu acesso de número 32


In [76]:
print('Olá, {nome}! Este é seu acesso de número {acessos}'.format(nome = 'Rodrigo', acessos = 32))

Olá, Rodrigo! Este é seu acesso de número 32


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [ ]:
nome = 'Rodrigo'
acessos = 32

In [78]:
print(f'Olá, {nome}! Este é seu acesso de número {acessos}')

Olá, Rodrigo! Este é seu acesso de número 32


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [97]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [92]:
type(Acessorios)

list

### Lista com tipos de dados variados

In [ ]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [94]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [95]:
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [96]:
Carros = [Carro_1, Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [98]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [99]:
'Rodas de liga' in Acessorios

True

In [100]:
'4 X 4' in Acessorios

False

In [101]:
'Rodas de liga' not in Acessorios

False

In [102]:
'4 X 4' not in Acessorios

True

## *A + B*

Concatena as listas *A* e *B*.

In [ ]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [104]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [105]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [106]:
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [107]:
len(Acessorios)

8

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [117]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [118]:
Acessorios[0]

'Rodas de liga'

In [119]:
Acessorios[1]

'Travas elétricas'

In [120]:
Acessorios[-1]

'Sensor de chuva'

In [121]:
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [122]:
Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [123]:
Carros[0][0]

'Jetta Variant'

In [124]:
Carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [125]:
Carros[0][-2][1]

'Travas elétricas'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [126]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [129]:
Acessorios[2:5]

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [130]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [131]:
Acessorios[:5]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

In [11]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

## *A.sort()*

Ordena a lista *A*.

In [12]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [13]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemento *x* no final da lista *A*.

In [14]:
Acessorios.append('4 X 4')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [15]:
Acessorios.pop()

'4 X 4'

In [16]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [17]:
Acessorios.pop(3)

'Rodas de liga'

In [18]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [19]:
Acessorios_2 = Acessorios
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [20]:
Acessorios_2.append('4 X 4')
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [21]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [22]:
Acessorios.pop()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [23]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [24]:
Acessorios_2 = Acessorios.copy()
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [25]:
Acessorios_2.append('4 X 4')
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [26]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [27]:
Acessorios_2 = Acessorios[:]
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [28]:
for acessorio in Acessorios:
    print(acessorio)

Ar condicionado
Bancos de couro
Piloto automático
Sensor crepuscular
Sensor de chuva
Sensor de estacionamento
Travas elétricas


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [29]:
range(10)

range(0, 10)

In [30]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
for i in range(10):
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [32]:
quadrado = []

In [33]:
for i in range(10):
    quadrado.append(i ** 2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [34]:
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [47]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [36]:
for lista in dados:
    print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [37]:
for lista in dados:
    for item in lista:
        print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [45]:
Acessorios = []

for lista in dados:
    for item in lista:
        Acessorios.append(item)

Acessorios


['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [43]:
list(set(Acessorios))

['Freios ABS',
 'Bancos de couro',
 'Central multimídia',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Controle de estabilidade',
 'Teto panorâmico',
 'Piloto automático',
 '4 X 4',
 'Câmera de estacionamento',
 'Sensor crepuscular',
 'Ar condicionado',
 'Painel digital',
 'Rodas de liga',
 'Vidros elétricos',
 'Câmbio automático',
 'Sensor de chuva']

### List comprehensions

In [48]:
list(set([item for lista in dados for intem in lista]))

['Vidros elétricos']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [2]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [53]:
zero_km_N = []
for lista in dados:
    if(lista[2] == False):
        zero_km_N.append(lista)
zero_km_N

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [54]:
zero_km_Y = []
for lista in dados:
    if(lista[2] == True):
        zero_km_Y.append(lista)
zero_km_Y


[['DS5', 2019, True], ['A5', 2019, True]]

### List comprehensions

In [56]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [17]:
zero_km_Y, zero_km_N = [], []

for lista in dados:
    if(lista[2] == True):
        zero_km_Y.append(lista)
    else:
        zero_km_N.append(lista)



In [18]:
zero_km_Y


[]

In [19]:
zero_km_N

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [20]:
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [21]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [22]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [23]:
A, B, C = [],[],[]

for lista in dados:
    if(lista[1]<= 2000):
        A.append(lista)
    elif(lista[1] >2000 and lista[1] <= 2010):
        B.append(lista)
    else:
        C.append(lista)

TypeError: '<=' not supported between instances of 'str' and 'int'

In [24]:
A

[]

In [25]:
B

[]

In [26]:
C

[]

In [27]:
A, B, C = [], [], []

for lista in dados:
    if(lista[1] <= 2000):
        A.append(lista)
    elif(2000 < lista[1] <= 2010):
        B.append(lista)
    else:
        C.append(lista)


TypeError: '<=' not supported between instances of 'str' and 'int'

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [28]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [29]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [30]:
import numpy as np

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [32]:
from numpy import arange

In [33]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [34]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [35]:
km = np.array([1000, 2300, 4987, 1500])

In [36]:
km

array([1000, 2300, 4987, 1500])

In [37]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [38]:
km.dtype

dtype('int32')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [39]:
km = np.loadtxt(fname= "data/carros-km.txt", dtype= int)

In [40]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [41]:
km.dtype

dtype('int32')

### Arrays com duas dimensões

In [42]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [43]:
Acessorios = np.array(dados)

In [44]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [45]:
km.shape

(258,)

In [46]:
Acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [47]:
np_array = np.arange(1000000)

In [48]:
py_list = list(range(1000000))


In [49]:
%time for _ in range(100): np_array *= 2


Wall time: 109 ms


In [50]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

Wall time: 13.3 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [51]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [52]:
# idade = 2021 - anos

In [53]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [54]:
idade = 2019 - anos

In [55]:
idade

array([16, 28, 29,  0, 13])

### Operações entre arrays

In [56]:
km_media = km / idade

C:\Users\gusta\AppData\Local\Temp/ipykernel_10960/4091711005.py:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = km / idade


In [57]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [58]:
44410 / (2019 - 2003)

2775.625

### Operações com arrays de duas dimensões

In [59]:
dados = np.array([km,anos])

In [60]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [61]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [62]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [63]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [64]:
km_media = dados[0] /(2019 - dados[1])

C:\Users\gusta\AppData\Local\Temp/ipykernel_10960/122350206.py:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = dados[0] /(2019 - dados[1])


In [65]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [66]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [67]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [68]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
contador[0]

0

In [70]:
item = 10
index = item -1
contador[index]

9

In [72]:
contador[-1]

9

In [73]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [75]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [78]:
dados[1, 2]

1990.0

In [79]:
dados[1][2]

1990.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [80]:
contador = np.arange(10)
contador


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
contador[1:4]

array([1, 2, 3])

In [83]:
contador[1:8:2]

array([1, 3, 5, 7])

In [84]:
contador[::2]

array([0, 2, 4, 6, 8])

In [85]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [86]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [88]:
dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [93]:
contador = np.arange(10)
contador


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
contador > 5 

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [95]:
contador[contador > 5]

array([6, 7, 8, 9])

In [96]:
contador[[False, False, False, False, False, False,  True,  True,  True,
          True]]


array([6, 7, 8, 9])

In [97]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [98]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [100]:
dados[1][[True, False, False,  True,  True]]


array([2003., 2019., 2006.])

In [101]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [102]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)


In [103]:
dados[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [104]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.],
       [2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [105]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [106]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [107]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [108]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [110]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [112]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [114]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [115]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
contador.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [125]:
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [126]:
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [127]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [128]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [132]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [133]:
np.array(info_carros).reshape((5, 2), order='F')


array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [134]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [136]:
dados_new.resize((3, 5), refcheck=False)

In [137]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [139]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1])
dados_new

C:\Users\gusta\AppData\Local\Temp/ipykernel_10960/2562693644.py:1: RuntimeWarning: invalid value encountered in true_divide
  dados_new[2] = dados_new[0] / (2019 - dados_new[1])


array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

In [140]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [143]:
anos = np.loadtxt(fname="data\carros-anos.txt", dtype=int)
km = np.loadtxt(fname="data\carros-km.txt")
valor = np.loadtxt(fname = "data\carros-valor.txt")


In [144]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [ ]:
dataset = np.column_stack((anos, km, valor))
dataset

In [146]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [148]:
np.mean(dataset, axis= 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis=1)

In [151]:
np.mean(dataset[:, 1])

44499.41472868217

In [152]:
np.mean(dataset[:, 2])


98960.51310077519

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [153]:
np.std(dataset[:, 2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [154]:
dataset.sum(axis= 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [155]:
dataset[:, 1].sum()


11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [156]:
np.sum(dataset, axis= 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [157]:
np.sum(dataset[:, 2])


25531812.38